name: whisper_feature_extractor
config_type: preprocessor
feature_size: 80
sampling_rate: 16000
padding: longest
padding_value: 0.0
padding_side: right
hop_length: 160
chunk_length: 30
n_fft: 400
return_attention_mask: false
